# Generated by Django 3.2.12 on 2022-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cir', models.CharField(max_length=200)),
                ('pos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cir', models.CharField(max_length=200)),
                ('start', models.CharField(max_length=200)),
                ('start_r', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
                ('end_r', models.CharField(max_length=200)),
            ],
        ),
    ]
