# Generated by Django 3.2.12 on 2022-02-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='cd',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
