# Generated by Django 4.0.2 on 2022-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_gab_defect_code_gab_lider_assy_gab_lider_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='eq',
            field=models.CharField(default='NX4e', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='per',
            name='cir',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
