# Generated by Django 4.0.2 on 2022-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_per_eq_alter_per_cir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per',
            name='cir',
            field=models.CharField(max_length=200),
        ),
    ]
