# Generated by Django 4.0.2 on 2022-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_alter_per_cir'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='eq',
            field=models.CharField(default='NX4e', max_length=200),
            preserve_default=False,
        ),
    ]
