# Generated by Django 4.0.2 on 2022-03-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_gab_eq'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='oid',
            field=models.CharField(default='12000', max_length=200),
            preserve_default=False,
        ),
    ]
