# Generated by Django 4.0.2 on 2022-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_gab_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='lot',
            field=models.CharField(default='34000000', max_length=50),
            preserve_default=False,
        ),
    ]
