# Generated by Django 4.0.2 on 2022-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_gab_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gab',
            name='ac_code',
            field=models.CharField(default='ac000000', max_length=50),
            preserve_default=False,
        ),
    ]
